version = 0.1
[default.deploy.parameters]
stack_name = "apigw-lambda-dynamodb-kinesis-lambda"
resolve_s3 = true
s3_prefix = "apigw-lambda-dynamodb-kinesis-lambda"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "KinesisStreamName=\"testDataStream\""
image_repositories = []
